version: '3.8' # نسخه Compose

services:
  nextjs:
    build:
      context: ./Student-attendance-system-next-js-main
    ports:
      - '3000:3000'
    depends_on:
      - nestjs
      - mysql
    networks:
      - mynetwork
    environment:
      NEXT_PUBLIC_API_URL: "http://nestjs:3001" # آدرس سرویس بک‌اند

  nestjs:
    build:
      context: ./project-name  # مسیر صحیح پروژه NestJS
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      DATABASE_URL: "mysql://user:userpassword@mysql:3306/mydatabase"
    restart: always  # در صورتی که NestJS مشکلی پیدا کند، دوباره راه‌اندازی می‌شود

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s  # زمان صبر کردن قبل از تست اولیه
    restart: always  # در صورتی که MySQL مشکلی پیدا کند، دوباره راه‌اندازی می‌شود

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"  # دسترسی به phpMyAdmin از پورت 8081
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
